refactoring

diff --git a/dot b/dot
--- a/dot
+++ b/dot
@@ -4,11 +4,6 @@ set -u
 set -Euo pipefail
 trap cleanup EXIT
 
-### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
-# Argbash is a bash code generator used to get arguments parsing right.
-# Argbash is FREE SOFTWARE, see https://argbash.io for more info
-# Generated online by https://argbash.io/generate
-
 ## dot specific functions
 setup_colors() {
   if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
@@ -53,23 +48,6 @@ cleanup() {
   # script cleanup here
 }
 
-## Back to argbash.io stuff
-#
-# # When called, the process ends.
-# Args:
-#   $1: The exit message (print to stderr)
-#   $2: The exit code (default is 1)
-# if env var _PRINT_HELP is set to 'yes', the usage is print to stderr (prior to $1)
-# Example:
-#   test -f "$_arg_infile" || _PRINT_HELP=yes die "Can't continue, have to supply file as an argument, got '$_arg_infile'" 4
-die()
-{
-  local _ret="${2:-1}"
-  test "${_PRINT_HELP:-no}" = yes && print_help >&2
-  echo -e "${RED}$1${NOFORMAT}" >&2
-  exit "${_ret}"
-}
-
 read_config_variable(){
   local KEY=$1
   local DEF=$2
@@ -93,6 +71,26 @@ load_config(){
     calling_dir="$PWD"
 }
 
+
+### START OF CODE GENERATED BY Argbash v2.9.0 one line above ###
+# Argbash is a bash code generator used to get arguments parsing right.
+# Argbash is FREE SOFTWARE, see https://argbash.io for more info
+# Generated online by https://argbash.io/generate
+#
+# # When called, the process ends.
+# Args:
+#   $1: The exit message (print to stderr)
+#   $2: The exit code (default is 1)
+# if env var _PRINT_HELP is set to 'yes', the usage is print to stderr (prior to $1)
+# Example:
+#   test -f "$_arg_infile" || _PRINT_HELP=yes die "Can't continue, have to supply file as an argument, got '$_arg_infile'" 4
+die()
+{
+  local _ret="${2:-1}"
+  test "${_PRINT_HELP:-no}" = yes && print_help >&2
+  echo -e "${RED}$1${NOFORMAT}" >&2
+  exit "${_ret}"
+}
 
 # Function that evaluates whether a value passed to it begins by a character
 # that is a short option of an argument the script knows about.
