fixed formatting

diff --git a/dot b/dot
--- a/dot
+++ b/dot
@@ -3,13 +3,17 @@
 set -u 
 set -Euo pipefail
 trap cleanup EXIT
+## TODO
+## Need to make sure debug outputs to stderr, right now it gets included in functions stdout 
+##and thus become part of variables that are assigned to function output
+
 
 ## dot specific functions
 setup_colors() {
   if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
-    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+    NOFORMAT="\e[0m" RED="\e[91m" GREEN="\e[92m" ORANGE="\e[93m" YELLOW="\e[96m"
   else
-    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+    NOFORMAT="" RED="" GREEN="" ORANGE="" YELLOW=""
   fi
 }
 
@@ -25,19 +29,33 @@ function ask_yes_or_no() {
     fi
 }
 
-msg() {
-  echo >&2 -e "${_print_indent}${1-}"
+# print one or two columns (set color before)
+print() {
+
+  if [[ -z ${2:-} ]]; then
+    printf "${3:-$NOFORMAT}%${INDENT:-0}s%s${NOFORMAT}\n" '' "${1-}" >&2 
+  else
+    printf "%${INDENT:-0}s%-30s ${3:-$NOFORMAT}%-30s${NOFORMAT}\n" '' "${1-}" "${2-}" >&2 
+  fi
+ 
+}
+
+warn() {
+  print "${1:-}" "${2:-}" "${YELLOW}"
+}
+
+err() {
+  print "${1:-}" "${2:-}" "${RED}"
+}
+
+success() {
+  print "${1:-}" "${2:-}" "${GREEN}"
 }
 
 debug() {
   if [ "$_arg_verbose" == "on" ]; then
-    echo >&2 -e "${_print_indent}${1-}"
+    INDENT=3 print "${1-}" "${2-}"
   fi
-}
-
-# print two columns
-msg2() {
-  echo >&2 -e "${_print_indent}${1-}\t\t\t: ${2-}" | expand -t 30  
 }
 
 cleanup() {
@@ -52,7 +70,7 @@ read_config_variable(){
   local KEY=$1
   local DEF=$2
   ret=$(git config -f "$DOT_CONFIG_FILE" "$KEY")
-  debug "$KEY == ${ret:=$DEF}"
+  debug "$KEY" ": ${ret:=$DEF}"
   echo "${ret}"
 
 }
@@ -88,7 +106,7 @@ die()
 {
   local _ret="${2:-1}"
   test "${_PRINT_HELP:-no}" = yes && print_help >&2
-  echo -e "${RED}$1${NOFORMAT}" >&2
+  err -e "${RED}$1${NOFORMAT}" >&2
   exit "${_ret}"
 }
 
@@ -313,17 +331,16 @@ assign_positional_args 1 "${_positionals[@]}"
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 
 _print_indent="\t"
-debug "${YELLOW}- Verbose -"
-debug "${YELLOW}dry run is $_arg_dry_run"
-debug "${YELLOW}force is $_arg_force"
-debug "${YELLOW}Value of command: $_arg_command"
-debug "${YELLOW}Value of package: $_arg_package"
-debug "${YELLOW}Value of args: ${_arg_arg[*]}"
-debug "${YELLOW}Number of args: ${#_arg_arg[*]}"
+debug "- Verbose -"
+debug "dry run is $_arg_dry_run"
+debug "force is $_arg_force"
+debug "Value of command: $_arg_command"
+debug "Value of package: $_arg_package"
+debug "Value of args: ${_arg_arg[*]}"
+debug "Number of args: ${#_arg_arg[*]}"
 
 load_config ## this might print some settings too
 
-debug "${NOFORMAT}"
 _print_indent=""
 
 ###################
@@ -391,10 +408,10 @@ add()
   [[ -z "${_arg_package-}" ]] && die "Missing required parameter: package"
 
   package_root=$(get_package_root "$_arg_package")
-  msg "Adding files to stow packet at ${package_root}"
+  print "Adding files to stow packet at ${package_root}"
 
   ## each arg is a file or a directory to add (relative to $calling_dir)  
-  msg "Validating files..."
+  print "Validating files..."
   valid_paths=( )
   for file_arg in "${_arg_arg[@]}"; do
     file_path=$(get_path_rel_caller "$file_arg")
@@ -403,30 +420,30 @@ add()
       ## make sure the file is not under .dotfiles path
       if isSubPath $dotfiles_dir $file_path ; then
         ## error
-          msg2 "${file_path}" "${RED}Cannot stow file in .dotfiles"
+          warn "${file_path}" "Cannot stow file in .dotfiles"
         else
-          msg2 "${file_path}" "OK"
+          sucess "${file_path}" "OK"
           valid_paths+=( "$file_path" )
       fi
      
     else
-      msg2 "${file_path}" "${RED}NOT FOUND"
+      err "${file_path}" "NOT FOUND"
       all_found=0
     fi
   done
   [[ $all_found -eq 0 ]] && die "Not all files were found, check paths!"
-  [[ "${#valid_paths[@]}" -eq 0 ]] && { msg "No files to stow" && return 0 ;}
+  [[ "${#valid_paths[@]}" -eq 0 ]] && { warn "No files to stow" && return 0 ;}
 
-  msg ""
-  msg "Moving files to stow repository: ${package_root}"
-  msg ""
+  print ""
+  print "Moving files to stow repository: ${package_root}"
+  print ""
 
   ## critical part
   for file in "${valid_paths[@]}"; do
     stow_path=$(get_path_rel_package "${package_root}" "${file_path}")
         
     mv -n -- "${file}" "${stow_path}" || die "Move failed for $file"
-    msg2 "${GREEN}Moved: $file" "-> $stow_path${NOFORMAT}"
+    success "Moved: $file" "-> $stow_path"
   done
   
   
@@ -437,7 +454,7 @@ add()
 restow_single()
 {
   #echo "stow -R -n --dir=${dotfiles_dir} --target=${target_dir} -S ${1} "
-  ${stowcmd} -R --dir=${dotfiles_dir} --target=${target_dir} -S ${1} > /dev/null && msg2 "\t$1" "${GREEN}Updated${NOFORMAT}" || msg2 "$1" "Failed"
+  ${stowcmd} -R --dir=${dotfiles_dir} --target=${target_dir} -S ${1} > /dev/null && success "$1" "Updated" || err "$1" "Failed"
   sleep 0.1
 }
 
@@ -447,7 +464,7 @@ restow()
   force_all_pkgs=${RESTOW_ALL:-}
   ## this command requires package to be specified either using args och -p/--package
   local num_pkgs
-  msg "Restoring ${GREEN}symlinks${NOFORMAT}" #. Packages=${_arg_arg[*]-all}...${NOFORMAT}"
+  print "Restoring symlinks" #. Packages=${_arg_arg[*]-all}...${NOFORMAT}"
   [[ -n "$force_all_pkgs" ]] && debug "forcing all packages"
   [[ -z "$_arg_package" ]] && debug "no package specified using -p"
 
@@ -462,13 +479,13 @@ restow()
     subdir_list=$(find . -maxdepth 1 -not -path '*/\.*' -type d \( ! -iname ".*" \) -printf "%f ")
     
     num_pkgs=$(wc -w <<< "$subdir_list")
-    echo "Found $num_pkgs packages:"
+    print "Found $num_pkgs packages:"
     for d in ${subdir_list}; do
       restow_single "$d"
     done 
   else
     if [ ${#_arg_arg[@]} -gt 0 ]; then
-      debug "Restowing list of packages: ${_arg_arg[*]-}"
+      debug "Restowing list of packages:" "${_arg_arg[*]-}"
       for p in "${_arg_arg[@]}"; do
         restow_single "$p"
       done 
@@ -492,31 +509,33 @@ git_sync(){
   
   ONLY_STATUS="ONLY_STATUS"
   MODE="${2:-SYNC}"
-  debug "MODE: $MODE"
+  debug "MODE" ": $MODE"
 
   debug "git status --porcelain=1 -uall"
   GIT_MODIFIED=$(git status --porcelain=1 -uall | awk '{print $1;}' | grep -E 'A|M|D' | head -1)
   GIT_UNTRACKED=$(git status --porcelain=1 -uall | awk '{print $1;}' | grep "?" | head -1)
   
-  [ -n "$GIT_MODIFIED" ] && msg "${YELLOW}Modified${NOFORMAT} files in local"
-  [ -n "$GIT_UNTRACKED" ] && msg "${RED}Untracked${NOFORMAT} files in local"
+  [ -n "$GIT_MODIFIED" ] && warn "Modified files in local"
+  [ -n "$GIT_UNTRACKED" ] && warn "Untracked files in local"
 
   ## Ask to commit files unless we are checking status only
   if [ "$MODE" != "$ONLY_STATUS" ]; then
-    if [[ ( -n "$GIT_UNTRACKED" || -n "$GIT_MODIFIED" ) && "yes" == $(ask_yes_or_no "Commit with comment \"${_arg_arg[*]-auto commit}\"?") ]]; then      
-      if [ "$MODE" != "$ONLY_STATUS" ]; then
-        debug "git add --quiet"
-        git add .
-      fi      
-      if [ "$MODE" != "$ONLY_STATUS" ]; then
-        debug "git commit -m \"${_arg_arg[*]-auto commit}\" --quiet"
-        git commit -m "${_arg_arg[*]-auto commit}" --quiet
+    if [[ ( -n "$GIT_UNTRACKED" || -n "$GIT_MODIFIED" ) ]]; then
+      if [[ "yes" == $(ask_yes_or_no "Commit with comment \"${_arg_arg[*]-auto commit}\"?") ]]; then      
+        if [ "$MODE" != "$ONLY_STATUS" ]; then
+          debug "git add --quiet"
+          git add .
+        fi      
+        if [ "$MODE" != "$ONLY_STATUS" ]; then
+          debug "git commit -m \"${_arg_arg[*]-auto commit}\" --quiet"
+          git commit -m "${_arg_arg[*]-auto commit}" --quiet
+        fi
+      else
+        debug "Commit declined by user"
       fi
-    else
-      debug "Commit declined by user"
     fi
   else
-    msg "Run \`dot sync\` to commit local changes"
+    print "Run \`dot sync\` to commit local changes"
   fi
  
   
@@ -526,14 +545,14 @@ git_sync(){
   
   # LOCAL
   LOCAL=$(git rev-parse @)  
-  [ "$MODE" == "$ONLY_STATUS" ] && msg "Local is at $LOCAL";
+  [ "$MODE" == "$ONLY_STATUS" ] && print "Local is at $LOCAL";
 
   debug "wait ${BG_PID}"
   wait ${BG_PID}
 
   # REMOTE
   REMOTE=$(git rev-parse "$UPSTREAM")  
-  [ "$MODE" == "$ONLY_STATUS" ] && msg "Remote is at $REMOTE";
+  [ "$MODE" == "$ONLY_STATUS" ] && print "Remote is at $REMOTE";
 
   # MERGE-BASE
   BASE=$(git merge-base @ "$UPSTREAM")
@@ -543,24 +562,24 @@ git_sync(){
   debug "git merge-base @ $1 returned $BASE"
 
   if [ $LOCAL = $REMOTE ]; then
-      msg "Git is ${GREEN}up-to-date${NOFORMAT}"
+      success "Your dotfiles git is up-to-date"
   elif [ $LOCAL = $BASE ]; then
       ## do correct output when dry-run
       if [[ "$MODE" == "$ONLY_STATUS" && ( -n "$GIT_MODIFIED" || -n "$GIT_UNTRACKED" ) ]]; then 
-        msg "Git need to ${YELLOW}pull${NOFORMAT} changes, and possibly rebase"
+        warn "Git need to pull changes, and possibly rebase"
       else
-        msg "Git need to ${YELLOW}pull${NOFORMAT} changes"
+        warn "Git need to pull changes"
       fi
       if [ "$MODE" != "$ONLY_STATUS" ]; then
         pull_ff
       fi
   elif [ $REMOTE = $BASE ]; then
-      msg "Git need to ${YELLOW}push${NOFORMAT} changes"
+      warn "Git need to push changes"
       if [ "$MODE" != "$ONLY_STATUS" ]; then
         push
       fi
   else
-      msg "Git is ${RED}diverged${NOFORMAT} - doing a pull followed by a push"
+      warn "Git is diverged - doing a pull followed by a push"
       if [ "$MODE" != "$ONLY_STATUS" ]; then
         pull_rebase
         push
@@ -590,7 +609,7 @@ push()
   #has_changes=$(commit_changes)
 
   #if [[ $has_changes -eq 1 ]]; then
-  msg "${GREEN}Pushing ${git_remote} ${git_branch}... (${_arg_arg[*]-auto commit})...${NOFORMAT}"
+  msg "Pushing ${git_remote} ${git_branch}... (${_arg_arg[*]-auto commit})..."
   git push "${git_remote}" "${git_branch}" --quiet
   debug "push done"
   #else
@@ -602,12 +621,12 @@ push()
 pull()
 { 
   
-  msg "${GREEN}Pulling...${NOFORMAT}"
+  print "Pulling..."
   PULL_MODE="${1:---ff-only}"
   debug "PULL_MODE: ${PULL_MODE}"
   #commit_changes
 
-  debug "${BLUE}Stashing existing changes...${NOFORMAT}"
+  debug "${BLUE}Stashing existing changes..."
   stash_result=$(git stash push -m "dot: Before pulling git")
   needs_pop=1
   if [ "$stash_result" = "No local changes to save" ]; then
@@ -616,7 +635,7 @@ pull()
   fi
 
   [ "${PULL_MODE}" == "--ff-only" ] && PULL_MODE_STR="Pulling updates" || PULL_MODE_STR="Fetching updates and rebasing";
-  msg "${BLUE}${PULL_MODE_STR} from ${git_remote} ${git_branch}...${NOFORMAT}"
+  print "${PULL_MODE_STR} from ${git_remote} ${git_branch}..."
   git pull "${git_remote}" "${git_branch}" "${PULL_MODE}" --quiet --recurse-submodules; result=$?
   
   if [[ 0 != "${result}" ]]; then
@@ -632,7 +651,7 @@ pull()
 
   unmerged_files=$(git diff --name-only --diff-filter=U)
   if [[ -n $unmerged_files ]]; then
-    msg "${RED}The following files have merge conflicts after popping the stash: ${NOFORMAT}"
+    err "${RED}The following files have merge conflicts after popping the stash: ${NOFORMAT}"
     echo
     printf %"s\n" "$unmerged_files"  # Ensure newlines are printed
   fi 
@@ -650,7 +669,7 @@ pull_rebase(){
 
 reset()
 {
-  echo "${GREEN}Delete all symlinks using stow. Packages=${args[*]-all}...${NOFORMAT}"
+  warn "Delete all symlinks using stow. Packages=${args[*]-all}..."
   stow --dir="${dotfiles_dir}" --target="${target_dir}" -D
 }
 
@@ -663,7 +682,7 @@ sync()
 }
 
 self_update() {
-    debug "${GREEN}Checking for newer version of dot...${NOFORMAT}"
+    print "Checking for newer version of dot..."
     local INSTALLPATH="$HOME/.local/share/dot"
     pushd "$INSTALLPATH" > /dev/null || die "Could not install dir: $INSTALLPATH"
 
@@ -671,18 +690,18 @@ self_update() {
 
     timeout 2s git diff --quiet --exit-code "origin/main" "dot"
     [ $? -eq 1 ] && {
-        debug "Found a new version of dot, updating..."
+        success "Found a new version of dot, updating..."
         git pull --force --quiet
         git checkout main --quiet
         git pull --force --quiet
-        msg "${GREEN}dot${NOFORMAT} has been updated"
+        success "dot has been updated!"
         popd > /dev/null || echo
         #exec "$SCRIPTNAME" "$@"
 
         # Now exit this old instance
         die "Update complete!"
     }
-    msg "${GREEN}dot${NOFORMAT} is already up-to-date"
+    print "dot is already up-to-date"
 }
 
 ### Enter dotfiles directory by default
@@ -729,6 +748,6 @@ case $_arg_command in
 esac
  
 
-debug "${GREEN} DONE ${NOFORMAT}"
+debug "DONE"
 #pushd -0 > /dev/null && dirs -c > /dev/null
 popd > /dev/null || exit
